### ISSUE TITLE
Atividade 15

### ISSUE THREAD

**Issue by B3nedito** [ProfRonan/lista-de-quadrados-perfeitos-B3nedito#2]
Print("Digite o número de quadrados perfeitos que você irá querer"
A= INT(input(">>>")) + 1
B= list(range(  1,a))
For A in B:
     Print(A**2)
      A +=1

**Comment by B3nedito** [comment]
Mandando as atividades pelo celular,  visto que não possuo computador

**Comment by SeuRonao** [comment]
A atividade é para ser feita dando um commit. Eu já disse em sala várias vezes, e inclusive já respondi que assim não podia.

Não era para ter deixado para a última hora e mesmo assim via celular daria para ter copiado e colado o código usando a interface web para fazer um commit.
